version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - MYSQL_DATABASE=dbname
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=ytrewq
    - MYSQL_HOST=db
    ports:
    - "8080:80"
    volumes:
    - .:/var/www
    - /var/www/vendor
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=ytrewq
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=ytrewq
    - MYSQL_DATABASE=dbname
    volumes:
    - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data: { driver: local }